name: Sport Bot Auto Check-in

on:
  schedule:
    - cron: '30 12 * * *' # 每天 UTC 时间 12:30 运行（北京时间 20:30）
  workflow_dispatch: # 手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests pycryptodome

      - name: 运行脚本
        env:
          USER: ${{ secrets.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          SMTP_AUTH_CODE: ${{ secrets.SMTP_AUTH_CODE }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
        run: python sport_bot.py
