name: XJTU Sport Bot

on:
  schedule:
    - cron: '0 12 * * *'  # 每天中午12:00执行（UTC时间，北京时间+8小时，即20:00）

  workflow_dispatch:  # 允许手动触发

jobs:
  run_bot:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 安装依赖
        run: pip install requests pycryptodome

      - name: 运行打卡脚本
        env:
          USER: ${{ secrets.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          LONGITUDE: ${{ secrets.LONGITUDE }}
          LATITUDE: ${{ secrets.LATITUDE }}
          SMTP_AUTH_CODE: ${{ secrets.SMTP_AUTH_CODE }}
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
        run: python sport_bot.py
